version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/patch_assembler"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      pip-patch-assembler-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/eval-scripts"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      pip-eval-scripts-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/ui_script"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      pip-ui-script-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
